### ISSUE TITLE
The plug-in cannot be enabled normally

### ISSUE THREAD

**Issue by xwinhyukx** [Sefiraat/DankTech2#1]
### Description 
Not functioning properly
Missing dank_packs.yml

### Server Log / Error Report 
https://pastebin.com/1kM617wv

### Environment (Required)
![2021-11-25 141627](https://user-images.githubusercontent.com/86247711/143392316-912227d1-b843-4c2b-b040-5ef26f7b4821.png)
- Minecraft Version : 1.17.1
- CS-CoreLib Version: N/A
- Slinefun Version: DEV -  984
- Plugin Version : DankTech2 Dev - 1

**Comment by Sefiraat** [comment]
Hi There,

Can you try again with Build 2? You will need to download this manually and remove the first from your server.
Let me know how you get on!

**Comment by xwinhyukx** [comment]
https://pastebin.com/Lud3pTrm

Can run normally.
Thanks

**Comment by Sefiraat** [comment]
Np, thanks for the report!
